addons:
  apt:
    sources:
      - boost-latest
      - george-edison55-precise-backports
    packages:
      - gcc
      - cmake-data
      - cmake
      - valgrind
      - libboost-all-dev
      - libbz2-dev
      - gettext

script:
     - cd src/Scripts/jenkins
     - bash -x ./dmdf_translation.sh
     - bash -x ./dmdf_generate_api_doc.sh

deploy:
    provider: releases
    api_key: ${api_key}
    file:
        - "./TheNorth/war3map_de.wts"
        - "./TheNorth/war3map_en.wts"
    skip_cleanup: true
    on:
        tags: true